name: Playwright Tests
on:
  # Run manually via GitHub API / Action tab
  workflow_dispatch:
  pull request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: moj-cloud-platform
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Clean npm cache
        run: npm cache clean --force
      - name: Install dependencies
        run: npm run setup
      - name: Install Playwright Browsers
        run: npx playwright install
      - name: Run Playwright tests
        id: tests
        run: npx playwright test --workers=1 --retries=0
        env:
          TZ: Europe/London
          ENV: dev

          # URLs
          E_SUPERVISION_API_URL: https://esupervision-api-dev.hmpps.service.justice.gov.uk
          PROBATION_CHECK_IN_URL: https://probation-check-in-dev.hmpps.service.justice.gov.uk
          AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk

          # Credentials
          AUTH_CLIENT_ID: ${{ secrets.AUTH_CLIENT_ID }}
          AUTH_CLIENT_SECRET: ${{ secrets.AUTH_CLIENT_SECRET }}

          # test data
          TEST_CRN: ${{secrets.TEST_CRN }}
          TEST_PERSON_FIRST_NAME: ${{secrets.TEST_PERSON_FIRST_NAME }}
          TEST_PERSON_LAST_NAME: ${{ secrets.TEST_PERSON_LAST_NAME }}
          TEST_PERSON_DOB: ${{secrets.TEST_PERSON_DOB }}

      - name: Publish JUnit report
        if: always()
        uses: mikepenz/action-junit-report@bccf2e31636835cf0874589931c4116687171386
        id: junit
        with:
          check_name: End-to-end test results
          report_paths: junit.xml
